import { QueryIntent } from "./types";
 
export interface IntentDefinition {
  intent: QueryIntent;
  questionType: string;
  examples: string[];
  requiredFields: string[];
  responsePattern: string;
  fallback: string;
  keywords: string[];
}
 
export const intentMap: IntentDefinition[] = [
  { intent: "inspection_baseline_date", questionType: "Baseline date", examples: ["When was the inspection baseline created?"], requiredFields: ["inspection_baseline.date"], responsePattern: "The inspection baseline was created on {date}.", fallback: "No inspection baseline date is recorded.", keywords: ["baseline", "inspection date", "first recorded"] },
  { intent: "inspection_provider", questionType: "Baseline source", examples: ["Who performed the inspection?"], requiredFields: ["inspection_baseline.provider_name"], responsePattern: "The inspection baseline was created by {provider}.", fallback: "No inspection provider is recorded.", keywords: ["who performed", "inspection provider", "created baseline"] },
  { intent: "property_record_start_date", questionType: "Record start", examples: ["When did the IQR record begin?"], requiredFields: ["property_record.start_date"], responsePattern: "The home record began on {date}.", fallback: "No start date is recorded for this home record.", keywords: ["record begin", "record start", "home record started"] },
  { intent: "system_list", questionType: "System inventory", examples: ["What systems are in this home?"], requiredFields: ["systems"], responsePattern: "This home record includes {system_list}.", fallback: "No systems are currently listed in the record.", keywords: ["systems", "major systems", "record include"] },
  { intent: "installation_date", questionType: "Install date", examples: ["When was the water heater installed?"], requiredFields: ["systems.install_date"], responsePattern: "The {system_name} was installed on {date}.", fallback: "No installation date is recorded for the {system_name}.", keywords: ["when was", "installed"] },
  { intent: "system_age", questionType: "System age", examples: ["How old is the HVAC?"], requiredFields: ["systems.age_estimate"], responsePattern: "The {system_name} is {age}.", fallback: "No age is recorded for the {system_name}.", keywords: ["how old", "age of"] },
  { intent: "manufacturer_model", questionType: "Equipment identity", examples: ["What model is the HVAC?"], requiredFields: ["systems.manufacturer", "systems.model"], responsePattern: "The {system_name} is a {manufacturer} {model}.", fallback: "No manufacturer or model is recorded for the {system_name}.", keywords: ["what brand", "what model", "equipment installed"] },
  { intent: "serial_number", questionType: "Equipment serial", examples: ["What is the serial number for the water heater?"], requiredFields: ["systems.serial_number"], responsePattern: "The serial number for the {system_name} is {serial}.", fallback: "No serial number is recorded for the {system_name}.", keywords: ["serial number"] },
  { intent: "device_location", questionType: "Physical location", examples: ["Where is the water heater?"], requiredFields: ["systems.location", "devices.location"], responsePattern: "The {device_name} is located at {location}.", fallback: "No location is recorded for the {device_name}.", keywords: ["where is", "where are", "location"] },
  { intent: "leak_sensor_locations", questionType: "Leak sensor locations", examples: ["Where are the leak sensors?"], requiredFields: ["devices"], responsePattern: "Leak sensors are installed at {locations}.", fallback: "No leak sensor locations are recorded.", keywords: ["leak sensors", "areas have leak sensors"] },
  { intent: "temp_humidity_sensor_locations", questionType: "Environmental sensor locations", examples: ["Where are the temp sensors?"], requiredFields: ["environmentalMonitoringZones"], responsePattern: "Temperature and humidity sensors are installed at {locations}.", fallback: "No temperature or humidity sensor locations are recorded.", keywords: ["temperature sensors", "temp humidity sensors", "temperature monitoring"] },
  { intent: "monitored_space", questionType: "Monitored room / zone", examples: ["What rooms are monitored?"], requiredFields: ["environmentalMonitoringZones"], responsePattern: "The monitored spaces are {locations}.", fallback: "No monitored spaces are recorded.", keywords: ["what rooms are monitored", "spaces have sensors", "areas being watched"] },
  { intent: "protected_water_points", questionType: "Water risk protection", examples: ["What water-risk points are protected?"], requiredFields: ["waterRiskPoints"], responsePattern: "The protected water-risk points are {protected_points}.", fallback: "No protected water-risk points are recorded.", keywords: ["water-risk points", "water points are covered", "protected water"] },
  { intent: "mitigation_devices", questionType: "Protection devices", examples: ["What mitigation devices are installed?"], requiredFields: ["mitigationDevices"], responsePattern: "The installed mitigation devices are {device_list}.", fallback: "No mitigation devices are recorded.", keywords: ["mitigation devices", "protection devices", "reduce risk"] },
  { intent: "shutoff_valve_locations", questionType: "Shutoff locations", examples: ["Where are the shutoff valves?"], requiredFields: ["waterRiskPoints"], responsePattern: "Shutoff valves are installed at {locations}.", fallback: "No shutoff valve locations are recorded.", keywords: ["shutoff valves", "automatic shutoff", "shutoff protection"] },
  { intent: "protected_fixture_status", questionType: "Specific protection status", examples: ["Is the dishwasher protected?"], requiredFields: ["waterRiskPoints.protection_status"], responsePattern: "The {fixture_name} is {status}.", fallback: "No protection status is recorded for the {fixture_name}.", keywords: ["is the dishwasher protected", "is the laundry protected", "have protection"] },
  { intent: "proof_of_prevention_status", questionType: "Verifiable mitigation", examples: ["What proof of prevention do we have?"], requiredFields: ["mitigationDevices"], responsePattern: "The documented prevention measures include {measures}.", fallback: "No documented prevention measures are recorded.", keywords: ["proof of prevention", "prevention measures", "protection on record"] },
  { intent: "environmental_monitoring_zones", questionType: "Environmental coverage", examples: ["What areas have environmental monitoring?"], requiredFields: ["environmentalMonitoringZones"], responsePattern: "Environmental monitoring covers {zones}.", fallback: "No environmental monitoring zones are recorded.", keywords: ["environmental monitoring", "temperature and humidity", "silent losses"] },
  { intent: "freezer_monitoring", questionType: "Freezer status", examples: ["Is the freezer monitored?"], requiredFields: ["environmentalMonitoringZones"], responsePattern: "The freezer monitoring status is {status}.", fallback: "No freezer monitoring is recorded.", keywords: ["freezer monitored", "freezer status"] },
  { intent: "wine_room_monitoring", questionType: "Wine storage status", examples: ["Is the wine room monitored?"], requiredFields: ["environmentalMonitoringZones"], responsePattern: "The wine storage monitoring status is {status}.", fallback: "No wine storage monitoring is recorded.", keywords: ["wine room monitored", "wine fridge"] },
  { intent: "av_rack_monitoring", questionType: "AV / network status", examples: ["Is the AV rack monitored?"], requiredFields: ["environmentalMonitoringZones"], responsePattern: "The AV or network rack monitoring status is {status}.", fallback: "No AV or network rack monitoring is recorded.", keywords: ["av rack monitored", "server rack", "network rack"] },
  { intent: "art_collection_monitoring", questionType: "Sensitive collection status", examples: ["Is the art room monitored?"], requiredFields: ["environmentalMonitoringZones"], responsePattern: "The collection monitoring status is {status}.", fallback: "No monitoring is recorded for that collection area.", keywords: ["art room monitored", "collections monitored"] },
  { intent: "last_service_event", questionType: "Most recent service", examples: ["What was the last service event?"], requiredFields: ["serviceEvents"], responsePattern: "The last service event was {event} on {date}.", fallback: "No service events are recorded.", keywords: ["last service", "serviced most recently", "what happened last"] },
  { intent: "service_history", questionType: "Full service history", examples: ["Show me the service history for the HVAC."], requiredFields: ["systems.service_history"], responsePattern: "The service history for the {system_name} includes {history_summary}.", fallback: "No service history is recorded for the {system_name}.", keywords: ["service history"] },
  { intent: "replacement_history", questionType: "Replacement events", examples: ["Has the water heater been replaced?"], requiredFields: ["systems.replacement_history"], responsePattern: "The replacement history includes {replacement_summary}.", fallback: "No replacement history is recorded.", keywords: ["replaced", "replacement history"] },
  { intent: "last_update_change", questionType: "Recent record changes", examples: ["What changed last?"], requiredFields: ["timeline"], responsePattern: "The most recent change was {change_summary}.", fallback: "No recent changes are recorded.", keywords: ["changed last", "latest update", "added most recently"] },
  { intent: "yearly_update_summary", questionType: "Last yearly review", examples: ["What happened in the last yearly update?"], requiredFields: ["yearlyUpdate.summary"], responsePattern: "The last yearly update included {summary}.", fallback: "No yearly update summary is recorded.", keywords: ["last yearly update", "yearly update summary"] },
  { intent: "yearly_update_date", questionType: "Last update date", examples: ["When was the last yearly update?"], requiredFields: ["yearlyUpdate.date"], responsePattern: "The last yearly update was completed on {date}.", fallback: "No yearly update date is recorded.", keywords: ["when was the last yearly update", "home record last reviewed"] },
  { intent: "yearly_update_verification_status", questionType: "Verification result", examples: ["Is the yearly update current?"], requiredFields: ["yearlyUpdate.verification_status"], responsePattern: "The yearly update status is {status}.", fallback: "No yearly update status is recorded.", keywords: ["yearly update current", "verified this year", "update completed"] },
  { intent: "sensor_status", questionType: "Device status", examples: ["Are the leak sensors active?"], requiredFields: ["devices.status"], responsePattern: "The {sensor_type} status is {status}.", fallback: "No status is recorded for the {sensor_type}.", keywords: ["sensors active", "devices online", "status of the temperature sensors"] },
  { intent: "battery_status", questionType: "Battery condition", examples: ["Do any sensors need battery replacement?"], requiredFields: ["devices.battery_status"], responsePattern: "The battery status for the {sensor_type} is {status}.", fallback: "No battery status is recorded for the {sensor_type}.", keywords: ["battery status", "battery replacement"] },
  { intent: "protection_verification_date", questionType: "Last verification", examples: ["When was the dishwasher protection last verified?"], requiredFields: ["waterRiskPoints.last_verified"], responsePattern: "The {device_name} was last verified on {date}.", fallback: "No verification date is recorded for the {device_name}.", keywords: ["last verified", "when were the sensors checked"] },
  { intent: "unresolved_issues", questionType: "Outstanding issues", examples: ["Are there any unresolved issues?"], requiredFields: ["issues.unresolved"], responsePattern: "The unresolved issues are {issue_list}.", fallback: "No unresolved issues are recorded.", keywords: ["unresolved issues", "still needs attention", "problems are still open"] },
  { intent: "needs_attention", questionType: "Action needed", examples: ["What needs attention?"], requiredFields: ["attentionItems"], responsePattern: "Items needing attention include {attention_list}.", fallback: "No items currently need attention.", keywords: ["needs attention", "overdue", "look at next"] },
  { intent: "what_is_monitored", questionType: "Monitoring summary", examples: ["What is being monitored?"], requiredFields: ["environmentalMonitoringZones"], responsePattern: "Monitoring currently covers {coverage_list}.", fallback: "No monitoring coverage is recorded.", keywords: ["what is monitored", "sensors cover", "parts of the home are monitored"] },
  { intent: "what_is_protected", questionType: "Protection summary", examples: ["What is protected in this house?"], requiredFields: ["waterRiskPoints"], responsePattern: "Protection is currently installed at {coverage_list}.", fallback: "No protection coverage is recorded.", keywords: ["what is protected", "areas have mitigation", "protection is installed"] },
  { intent: "home_record_summary", questionType: "Whole-record summary", examples: ["Tell me about this home."], requiredFields: ["property_record", "inspection_baseline", "systems"], responsePattern: "This home record includes {summary}.", fallback: "The home record does not yet contain enough information for a summary.", keywords: ["summarize this house", "tell me about this home", "what do we know about this house"] },
  { intent: "risk_profile_summary", questionType: "Risk overview", examples: ["What is the risk profile of this house?"], requiredFields: ["waterRiskPoints", "issues.unresolved"], responsePattern: "The current risk profile includes {risk_summary}.", fallback: "No risk profile summary is recorded yet.", keywords: ["risk profile", "main risks and protections", "house risk summary"] },
  { intent: "timeline_summary", questionType: "Record timeline", examples: ["Show me the house timeline."], requiredFields: ["timeline"], responsePattern: "The property timeline includes {timeline_summary}.", fallback: "No timeline events are recorded.", keywords: ["timeline", "over time", "record timeline"] },
  { intent: "event_by_date", questionType: "Specific dated event", examples: ["What happened in 2026?"], requiredFields: ["timeline"], responsePattern: "On {date_or_period}, the recorded event was {event}.", fallback: "No event is recorded for that date or period.", keywords: ["what happened in", "event from", "added last march"] }
];
